[".config/dotfiles/submodules/powerlevel10k"]
    type = "git-repo"
    url = "https://github.com/romkatv/powerlevel10k.git"
    exact = true
    stripComponents = 1
    refreshPeriod = "24h"
[".config/dotfiles/submodules/.tmux"]
    type = "git-repo"
    url = "https://github.com/gpakosz/.tmux.git"
    exact = true
    stripComponents = 1
    refreshPeriod = "24h"