#!/bin/sh

userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# merge in defaults and keymaps
if [ -f $sysresources ]; then
  xrdb -merge $sysresources
fi

if [ -f $sysmodmap ]; then
  xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then
  xrdb -merge "$userresources"
fi

if [ -f "$usermodmap" ]; then
  xmodmap "$usermodmap"
fi

# start some nice programs
if [ -d /etc/X11/xinit/xinitrc.d ] ; then
  for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
    # shellcheck source=/dev/null
    [ -x "$f" ] && source "$f"
  done
  unset f
fi

# Android Studio transparent bug
export _JAVA_AWT_WM_NONREPARENTING=1

# Keyboard layout for G913 TKL
setxkbmap -model 106 -layout jp -option caps:ctrl_modifier,japan &

# xset
xset r rate 200 30 &

# fehbg
source ~/.fehbg

# picom
picom &

# Display Manager
$HOME/bin/dwmbar &
dwm
